(function(){
  const $ = (s,root=document)=>root.querySelector(s);
  const $$ = (s,root=document)=>Array.from(root.querySelectorAll(s));

  // Built-in interface language packs. These are authored platform translations, not Google Translate.
  const languagePacks = {
    en:{dir:'ltr',navPassport:'Digital passport',navPortal:'Global portal',navSecurity:'Security',navContact:'Contact',getStarted:'Get started',heroEyebrow:'A NEW WAY TO CONNECT DIGITALLY',heroTitle:'ONE ID.<br><span>ONE PASSPORT.</span><br>GLOBAL ACCESS.',heroLead:'Your digital identity for a more connected world.',createId:'Create your digital ID',discoverHow:'Discover how it works',scrollExplore:'SCROLL TO EXPLORE ↓',howEyebrow:'SIMPLE BY DESIGN',howTitle:'Your digital journey,<br><span>in a few clear steps.</span>',step1Title:'Choose your pass',step2Title:'Build your profile',step3Title:'Preview your passport',step4Title:'Explore the portal',passportEyebrow:'YOUR PROFILE STARTS HERE',passportTitle:'Choose your <span>digital pass.</span>',profileDetails:'Profile details',profileIntro:'Enter your details and an optional photo. Review everything before saving.',fullNameLabel:'Full name',birthDateLabel:'Date of birth',nationalityLabel:'Nationality / country',previewButton:'Preview my digital pass',livePreview:'LIVE PREVIEW',sampleDesign:'SAMPLE DESIGN',printPreview:'Print / save preview',globalEyebrow:'THE GLOBAL PORTAL',globalTitle:'Explore a world of <span>possibilities.</span>',contactEyebrow:'WE ARE LISTENING',contactTitle:'Citizen support<br><span>& feedback.</span>',contactTeam:'Contact the team',contactNameLabel:'Your name *',contactEmailLabel:'Email address *',contactTopicLabel:'What is this about? *',contactMessageLabel:'Your message *',prepareMessage:'Prepare message',legalWiderruf:'Widerruf',legalAgb:'AGB',legalPrivacy:'Datenschutz',legalImpressum:'Impressum',cookieSettings:'Cookie settings',copyright:'© 2026 digital-future.ai',topicComplaint:'Complaint',topicRequest:'Service request',topicTechnical:'Technical problem',topicPrivacy:'Privacy request',topicSuggestion:'Suggestion or feedback',topicOther:'Other question'},
    de:{dir:'ltr',navPassport:'Digitaler Pass',navPortal:'Globales Portal',navSecurity:'Sicherheit',navContact:'Kontakt',getStarted:'Loslegen',heroEyebrow:'EINE NEUE ART, DIGITAL VERBUNDEN ZU SEIN',heroTitle:'EINE ID.<br><span>EIN PASS.</span><br>GLOBALER ZUGANG.',heroLead:'Ihre digitale Identität für eine stärker vernetzte Welt.',createId:'Digitale ID erstellen',discoverHow:'So funktioniert es',scrollExplore:'WEITER ENTDECKEN ↓',howEyebrow:'EINFACH GESTALTET',howTitle:'Ihre digitale Reise<br><span>in wenigen Schritten.</span>',step1Title:'Pass auswählen',step2Title:'Profil erstellen',step3Title:'Pass ansehen',step4Title:'Portal entdecken',passportEyebrow:'HIER BEGINNT IHR PROFIL',passportTitle:'Wählen Sie Ihren <span>digitalen Pass.</span>',profileDetails:'Profildaten',profileIntro:'Geben Sie Ihre Daten und optional ein Foto ein. Prüfen Sie alles vor dem Speichern.',fullNameLabel:'Vollständiger Name',birthDateLabel:'Geburtsdatum',nationalityLabel:'Nationalität / Land',previewButton:'Digitalen Pass anzeigen',livePreview:'LIVE-VORSCHAU',sampleDesign:'MUSTERDESIGN',printPreview:'Vorschau drucken / speichern',globalEyebrow:'DAS GLOBALE PORTAL',globalTitle:'Entdecken Sie neue <span>Möglichkeiten.</span>',contactEyebrow:'WIR HÖREN ZU',contactTitle:'Bürgerkontakt<br><span>& Feedback.</span>',contactTeam:'Team kontaktieren',contactNameLabel:'Ihr Name *',contactEmailLabel:'E-Mail-Adresse *',contactTopicLabel:'Worum geht es? *',contactMessageLabel:'Ihre Nachricht *',prepareMessage:'Nachricht vorbereiten',legalWiderruf:'Widerruf',legalAgb:'AGB',legalPrivacy:'Datenschutz',legalImpressum:'Impressum',cookieSettings:'Cookie-Einstellungen',copyright:'© 2026 digital-future.ai',topicComplaint:'Beschwerde',topicRequest:'Serviceanfrage',topicTechnical:'Technisches Problem',topicPrivacy:'Datenschutzanfrage',topicSuggestion:'Vorschlag oder Feedback',topicOther:'Sonstige Frage'},
    ar:{dir:'rtl',navPassport:'جواز الهوية الرقمية',navPortal:'البوابة العالمية',navSecurity:'الأمان',navContact:'تواصل معنا',getStarted:'ابدأ الآن',heroEyebrow:'طريقة جديدة للتواصل الرقمي',heroTitle:'هوية واحدة.<br><span>جواز رقمي واحد.</span><br>وصول عالمي.',heroLead:'هويتك الرقمية لعالم أكثر ترابطًا.',createId:'أنشئ هويتك الرقمية',discoverHow:'اكتشف طريقة العمل',scrollExplore:'تابع الاستكشاف ↓',howEyebrow:'ببساطة ووضوح',howTitle:'رحلتك الرقمية<br><span>في خطوات واضحة.</span>',step1Title:'اختر نوع الجواز',step2Title:'أنشئ ملفك الشخصي',step3Title:'عاين الجواز الرقمي',step4Title:'استكشف البوابة',passportEyebrow:'ابدأ ملفك الشخصي هنا',passportTitle:'اختر <span>جوازك الرقمي.</span>',profileDetails:'بيانات الملف الشخصي',profileIntro:'أدخل بياناتك وأضف صورة اختياريًا. راجع المعلومات قبل الحفظ.',fullNameLabel:'الاسم الكامل',birthDateLabel:'تاريخ الميلاد',nationalityLabel:'الجنسية / الدولة',previewButton:'معاينة الجواز الرقمي',livePreview:'معاينة مباشرة',sampleDesign:'تصميم تجريبي',printPreview:'طباعة / حفظ المعاينة',globalEyebrow:'البوابة العالمية',globalTitle:'اكتشف عالمًا من <span>الفرص.</span>',contactEyebrow:'نحن نستمع إليك',contactTitle:'دعم المواطنين<br><span>والملاحظات.</span>',contactTeam:'تواصل مع الفريق',contactNameLabel:'اسمك *',contactEmailLabel:'البريد الإلكتروني *',contactTopicLabel:'ما موضوع رسالتك؟ *',contactMessageLabel:'رسالتك *',prepareMessage:'تجهيز الرسالة',legalWiderruf:'حق التراجع',legalAgb:'الشروط والأحكام',legalPrivacy:'الخصوصية',legalImpressum:'بيانات المشغّل',cookieSettings:'إعدادات ملفات الارتباط',copyright:'© 2026 digital-future.ai',topicComplaint:'شكوى',topicRequest:'طلب خدمة',topicTechnical:'مشكلة تقنية',topicPrivacy:'طلب متعلق بالخصوصية',topicSuggestion:'اقتراح أو ملاحظات',topicOther:'استفسار آخر'},
    fr:{dir:'ltr',navPassport:'Passeport numérique',navPortal:'Portail mondial',navSecurity:'Sécurité',navContact:'Contact',getStarted:'Commencer',heroEyebrow:'UNE NOUVELLE FAÇON DE SE CONNECTER',heroTitle:'UNE ID.<br><span>UN PASSEPORT.</span><br>ACCÈS MONDIAL.',heroLead:'Votre identité numérique pour un monde plus connecté.',createId:'Créer votre ID numérique',discoverHow:'Découvrir le fonctionnement',scrollExplore:'DÉCOUVRIR ↓',howEyebrow:'LA SIMPLICITÉ AVANT TOUT',howTitle:'Votre parcours numérique,<br><span>en quelques étapes.</span>',step1Title:'Choisir votre pass',step2Title:'Créer votre profil',step3Title:'Prévisualiser le passeport',step4Title:'Explorer le portail',passportEyebrow:'VOTRE PROFIL COMMENCE ICI',passportTitle:'Choisissez votre <span>pass numérique.</span>',profileDetails:'Détails du profil',profileIntro:'Saisissez vos informations et une photo facultative. Vérifiez tout avant de sauvegarder.',fullNameLabel:'Nom complet',birthDateLabel:'Date de naissance',nationalityLabel:'Nationalité / pays',previewButton:'Prévisualiser mon pass',livePreview:'APERÇU EN DIRECT',sampleDesign:'MODÈLE',printPreview:'Imprimer / enregistrer l’aperçu',globalEyebrow:'LE PORTAIL MONDIAL',globalTitle:'Explorez un monde de <span>possibilités.</span>',contactEyebrow:'NOUS VOUS ÉCOUTONS',contactTitle:'Assistance citoyenne<br><span>et commentaires.</span>',contactTeam:'Contacter l’équipe',contactNameLabel:'Votre nom *',contactEmailLabel:'Adresse e-mail *',contactTopicLabel:'Quel est le sujet ? *',contactMessageLabel:'Votre message *',prepareMessage:'Préparer le message',legalWiderruf:'Rétractation',legalAgb:'Conditions générales',legalPrivacy:'Confidentialité',legalImpressum:'Mentions légales',cookieSettings:'Paramètres des cookies',copyright:'© 2026 digital-future.ai',topicComplaint:'Réclamation',topicRequest:'Demande de service',topicTechnical:'Problème technique',topicPrivacy:'Demande de confidentialité',topicSuggestion:'Suggestion ou commentaire',topicOther:'Autre question'},
    es:{dir:'ltr',navPassport:'Pasaporte digital',navPortal:'Portal global',navSecurity:'Seguridad',navContact:'Contacto',getStarted:'Comenzar',heroEyebrow:'UNA NUEVA FORMA DE CONECTARSE DIGITALMENTE',heroTitle:'UNA ID.<br><span>UN PASAPORTE.</span><br>ACCESO GLOBAL.',heroLead:'Tu identidad digital para un mundo más conectado.',createId:'Crear tu ID digital',discoverHow:'Descubre cómo funciona',scrollExplore:'EXPLORAR ↓',howEyebrow:'SENCILLO POR DISEÑO',howTitle:'Tu recorrido digital,<br><span>en unos pocos pasos.</span>',step1Title:'Elige tu pase',step2Title:'Crea tu perfil',step3Title:'Previsualiza tu pasaporte',step4Title:'Explora el portal',passportEyebrow:'TU PERFIL EMPIEZA AQUÍ',passportTitle:'Elige tu <span>pase digital.</span>',profileDetails:'Datos del perfil',profileIntro:'Introduce tus datos y una foto opcional. Revisa todo antes de guardar.',fullNameLabel:'Nombre completo',birthDateLabel:'Fecha de nacimiento',nationalityLabel:'Nacionalidad / país',previewButton:'Previsualizar mi pase',livePreview:'VISTA PREVIA',sampleDesign:'DISEÑO DE MUESTRA',printPreview:'Imprimir / guardar vista previa',globalEyebrow:'EL PORTAL GLOBAL',globalTitle:'Explora un mundo de <span>posibilidades.</span>',contactEyebrow:'TE ESCUCHAMOS',contactTitle:'Atención ciudadana<br><span>y comentarios.</span>',contactTeam:'Contactar con el equipo',contactNameLabel:'Tu nombre *',contactEmailLabel:'Correo electrónico *',contactTopicLabel:'¿De qué se trata? *',contactMessageLabel:'Tu mensaje *',prepareMessage:'Preparar mensaje',legalWiderruf:'Desistimiento',legalAgb:'Términos y condiciones',legalPrivacy:'Privacidad',legalImpressum:'Aviso legal',cookieSettings:'Configuración de cookies',copyright:'© 2026 digital-future.ai',topicComplaint:'Queja',topicRequest:'Solicitud de servicio',topicTechnical:'Problema técnico',topicPrivacy:'Solicitud de privacidad',topicSuggestion:'Sugerencia o comentario',topicOther:'Otra consulta'},
    tr:{dir:'ltr',navPassport:'Dijital pasaport',navPortal:'Küresel portal',navSecurity:'Güvenlik',navContact:'İletişim',getStarted:'Başla',heroEyebrow:'DİJİTAL BAĞLANTI İÇİN YENİ BİR YOL',heroTitle:'TEK KİMLİK.<br><span>TEK PASAPORT.</span><br>KÜRESEL ERİŞİM.',heroLead:'Daha bağlantılı bir dünya için dijital kimliğiniz.',createId:'Dijital kimliğini oluştur',discoverHow:'Nasıl çalıştığını keşfet',scrollExplore:'KEŞFET ↓',howEyebrow:'SADE VE KOLAY',howTitle:'Dijital yolculuğunuz,<br><span>birkaç kolay adımda.</span>',step1Title:'Kartını seç',step2Title:'Profilini oluştur',step3Title:'Pasaportu önizle',step4Title:'Portalı keşfet',passportEyebrow:'PROFİLİN BURADA BAŞLIYOR',passportTitle:'<span>Dijital kartını</span> seç.',profileDetails:'Profil bilgileri',profileIntro:'Bilgilerinizi ve isteğe bağlı fotoğrafınızı ekleyin. Kaydetmeden önce kontrol edin.',fullNameLabel:'Ad soyad',birthDateLabel:'Doğum tarihi',nationalityLabel:'Uyruk / ülke',previewButton:'Dijital kartı önizle',livePreview:'CANLI ÖNİZLEME',sampleDesign:'ÖRNEK TASARIM',printPreview:'Önizlemeyi yazdır / kaydet',globalEyebrow:'KÜRESEL PORTAL',globalTitle:'Yeni <span>olanaklar</span> keşfedin.',contactEyebrow:'SİZİ DİNLİYORUZ',contactTitle:'Vatandaş desteği<br><span>ve geri bildirim.</span>',contactTeam:'Ekiple iletişim',contactNameLabel:'Adınız *',contactEmailLabel:'E-posta adresi *',contactTopicLabel:'Konu nedir? *',contactMessageLabel:'Mesajınız *',prepareMessage:'Mesajı hazırla',legalWiderruf:'Cayma hakkı',legalAgb:'Şartlar ve koşullar',legalPrivacy:'Gizlilik',legalImpressum:'Yasal bilgiler',cookieSettings:'Çerez ayarları',copyright:'© 2026 digital-future.ai',topicComplaint:'Şikâyet',topicRequest:'Hizmet talebi',topicTechnical:'Teknik sorun',topicPrivacy:'Gizlilik talebi',topicSuggestion:'Öneri veya geri bildirim',topicOther:'Diğer soru'},
    it:{dir:'ltr',navPassport:'Passaporto digitale',navPortal:'Portale globale',navSecurity:'Sicurezza',navContact:'Contatti',getStarted:'Inizia',heroEyebrow:'UN NUOVO MODO DI CONNETTERSI DIGITALMENTE',heroTitle:'UN ID.<br><span>UN PASSAPORTO.</span><br>ACCESSO GLOBALE.',heroLead:'La tua identità digitale per un mondo più connesso.',createId:'Crea la tua ID digitale',discoverHow:'Scopri come funziona',scrollExplore:'ESPLORA ↓',howEyebrow:'SEMPLICE PER DESIGN',howTitle:'Il tuo percorso digitale,<br><span>in pochi passaggi.</span>',step1Title:'Scegli il pass',step2Title:'Crea il profilo',step3Title:'Anteprima del passaporto',step4Title:'Esplora il portale',passportEyebrow:'IL TUO PROFILO INIZIA QUI',passportTitle:'Scegli il tuo <span>pass digitale.</span>',profileDetails:'Dettagli del profilo',profileIntro:'Inserisci i tuoi dati e una foto facoltativa. Controlla tutto prima di salvare.',fullNameLabel:'Nome completo',birthDateLabel:'Data di nascita',nationalityLabel:'Nazionalità / paese',previewButton:'Anteprima del pass digitale',livePreview:'ANTEPRIMA LIVE',sampleDesign:'DESIGN ESEMPIO',printPreview:'Stampa / salva anteprima',globalEyebrow:'IL PORTALE GLOBALE',globalTitle:'Esplora un mondo di <span>possibilità.</span>',contactEyebrow:'TI ASCOLTIAMO',contactTitle:'Assistenza cittadini<br><span>e feedback.</span>',contactTeam:'Contatta il team',contactNameLabel:'Il tuo nome *',contactEmailLabel:'Indirizzo e-mail *',contactTopicLabel:'Di cosa si tratta? *',contactMessageLabel:'Il tuo messaggio *',prepareMessage:'Prepara il messaggio',legalWiderruf:'Recesso',legalAgb:'Termini e condizioni',legalPrivacy:'Privacy',legalImpressum:'Note legali',cookieSettings:'Impostazioni cookie',copyright:'© 2026 digital-future.ai',topicComplaint:'Reclamo',topicRequest:'Richiesta di servizio',topicTechnical:'Problema tecnico',topicPrivacy:'Richiesta sulla privacy',topicSuggestion:'Suggerimento o feedback',topicOther:'Altra domanda'},
    pt:{dir:'ltr',navPassport:'Passaporte digital',navPortal:'Portal global',navSecurity:'Segurança',navContact:'Contacto',getStarted:'Começar',heroEyebrow:'UMA NOVA FORMA DE LIGAÇÃO DIGITAL',heroTitle:'UM ID.<br><span>UM PASSAPORTE.</span><br>ACESSO GLOBAL.',heroLead:'A sua identidade digital para um mundo mais conectado.',createId:'Criar o seu ID digital',discoverHow:'Descubra como funciona',scrollExplore:'EXPLORAR ↓',howEyebrow:'SIMPLES POR CONCEÇÃO',howTitle:'A sua jornada digital,<br><span>em poucos passos.</span>',step1Title:'Escolher o passe',step2Title:'Criar o perfil',step3Title:'Pré-visualizar o passaporte',step4Title:'Explorar o portal',passportEyebrow:'O SEU PERFIL COMEÇA AQUI',passportTitle:'Escolha o seu <span>passe digital.</span>',profileDetails:'Dados do perfil',profileIntro:'Introduza os seus dados e uma foto opcional. Reveja tudo antes de guardar.',fullNameLabel:'Nome completo',birthDateLabel:'Data de nascimento',nationalityLabel:'Nacionalidade / país',previewButton:'Pré-visualizar o passe digital',livePreview:'PRÉ-VISUALIZAÇÃO',sampleDesign:'DESIGN DE EXEMPLO',printPreview:'Imprimir / guardar pré-visualização',globalEyebrow:'O PORTAL GLOBAL',globalTitle:'Explore um mundo de <span>possibilidades.</span>',contactEyebrow:'ESTAMOS A OUVIR',contactTitle:'Apoio ao cidadão<br><span>e comentários.</span>',contactTeam:'Contactar a equipa',contactNameLabel:'O seu nome *',contactEmailLabel:'Endereço de e-mail *',contactTopicLabel:'Qual é o assunto? *',contactMessageLabel:'A sua mensagem *',prepareMessage:'Preparar mensagem',legalWiderruf:'Direito de retratação',legalAgb:'Termos e condições',legalPrivacy:'Privacidade',legalImpressum:'Informações legais',cookieSettings:'Definições de cookies',copyright:'© 2026 digital-future.ai',topicComplaint:'Reclamação',topicRequest:'Pedido de serviço',topicTechnical:'Problema técnico',topicPrivacy:'Pedido de privacidade',topicSuggestion:'Sugestão ou comentário',topicOther:'Outra questão'},
    ru:{dir:'ltr',navPassport:'Цифровой паспорт',navPortal:'Глобальный портал',navSecurity:'Безопасность',navContact:'Контакты',getStarted:'Начать',heroEyebrow:'НОВЫЙ СПОСОБ ЦИФРОВОГО ОБЩЕНИЯ',heroTitle:'ОДИН ID.<br><span>ОДИН ПАСПОРТ.</span><br>ГЛОБАЛЬНЫЙ ДОСТУП.',heroLead:'Ваша цифровая идентичность для более связанного мира.',createId:'Создать цифровой ID',discoverHow:'Как это работает',scrollExplore:'ИССЛЕДОВАТЬ ↓',howEyebrow:'ПРОСТО И ПОНЯТНО',howTitle:'Ваш цифровой путь<br><span>в несколько шагов.</span>',step1Title:'Выберите пропуск',step2Title:'Создайте профиль',step3Title:'Просмотрите паспорт',step4Title:'Откройте портал',passportEyebrow:'НАЧНИТЕ СОЗДАНИЕ ПРОФИЛЯ',passportTitle:'Выберите свой <span>цифровой пропуск.</span>',profileDetails:'Данные профиля',profileIntro:'Введите данные и при желании добавьте фото. Проверьте всё перед сохранением.',fullNameLabel:'Полное имя',birthDateLabel:'Дата рождения',nationalityLabel:'Гражданство / страна',previewButton:'Предпросмотр цифрового пропуска',livePreview:'ПРЕДПРОСМОТР',sampleDesign:'ОБРАЗЕЦ ДИЗАЙНА',printPreview:'Печать / сохранение предпросмотра',globalEyebrow:'ГЛОБАЛЬНЫЙ ПОРТАЛ',globalTitle:'Откройте мир <span>возможностей.</span>',contactEyebrow:'МЫ ВАС СЛУШАЕМ',contactTitle:'Поддержка граждан<br><span>и обратная связь.</span>',contactTeam:'Связаться с командой',contactNameLabel:'Ваше имя *',contactEmailLabel:'Электронная почта *',contactTopicLabel:'Тема обращения *',contactMessageLabel:'Ваше сообщение *',prepareMessage:'Подготовить сообщение',legalWiderruf:'Отказ от договора',legalAgb:'Условия использования',legalPrivacy:'Конфиденциальность',legalImpressum:'Юридическая информация',cookieSettings:'Настройки cookies',copyright:'© 2026 digital-future.ai',topicComplaint:'Жалоба',topicRequest:'Запрос услуги',topicTechnical:'Техническая проблема',topicPrivacy:'Запрос о конфиденциальности',topicSuggestion:'Предложение или отзыв',topicOther:'Другой вопрос'},
    zh:{dir:'ltr',navPassport:'数字身份通行证',navPortal:'全球门户',navSecurity:'安全',navContact:'联系我们',getStarted:'开始使用',heroEyebrow:'连接数字世界的新方式',heroTitle:'一个身份。<br><span>一张数字通行证。</span><br>连接全球。',heroLead:'让您的数字身份连接更广阔的世界。',createId:'创建数字身份',discoverHow:'了解使用方式',scrollExplore:'继续探索 ↓',howEyebrow:'简单清晰的设计',howTitle:'您的数字旅程，<br><span>只需几个简单步骤。</span>',step1Title:'选择通行证',step2Title:'创建个人资料',step3Title:'预览数字通行证',step4Title:'探索全球门户',passportEyebrow:'从这里开始创建资料',passportTitle:'选择您的<span>数字通行证。</span>',profileDetails:'个人资料',profileIntro:'填写资料并可选上传照片。保存前请检查所有信息。',fullNameLabel:'姓名',birthDateLabel:'出生日期',nationalityLabel:'国籍 / 国家',previewButton:'预览数字通行证',livePreview:'实时预览',sampleDesign:'示例设计',printPreview:'打印 / 保存预览',globalEyebrow:'全球门户',globalTitle:'探索更多<span>可能性。</span>',contactEyebrow:'我们倾听您的声音',contactTitle:'公民支持<br><span>与意见反馈。</span>',contactTeam:'联系团队',contactNameLabel:'您的姓名 *',contactEmailLabel:'电子邮箱 *',contactTopicLabel:'咨询主题 *',contactMessageLabel:'您的留言 *',prepareMessage:'准备留言',legalWiderruf:'撤销权',legalAgb:'条款与条件',legalPrivacy:'隐私政策',legalImpressum:'法律声明',cookieSettings:'Cookie 设置',copyright:'© 2026 digital-future.ai',topicComplaint:'投诉',topicRequest:'服务请求',topicTechnical:'技术问题',topicPrivacy:'隐私请求',topicSuggestion:'建议或反馈',topicOther:'其他问题'}
  };
  function applyLanguage(code){
    const pack=languagePacks[code]||languagePacks.en;
    document.documentElement.lang=code;
    document.documentElement.dir=pack.dir||'ltr';
    document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(pack[key])el.textContent=pack[key];});
    document.querySelectorAll('[data-i18n-html]').forEach(el=>{const key=el.dataset.i18nHtml;if(pack[key])el.innerHTML=pack[key];});
    const chooser=$('#languageSelect'); if(chooser) chooser.value=code;
    try{sessionStorage.setItem('dfs-language',code)}catch(_){}
    const nm=$('#previewName'); if(nm && (!nm.dataset.userEdited || nm.textContent==='YOUR NAME'))nm.textContent=pack.profileHolder||'YOUR NAME';
  }
  const languageSelect=$('#languageSelect');
  if(languageSelect){
    let saved='en';try{saved=sessionStorage.getItem('dfs-language')||'en'}catch(_){}
    languageSelect.addEventListener('change',()=>applyLanguage(languageSelect.value));
    applyLanguage(saved);
  }

  const nav=$('#mainNav'), menu=$('#menuToggle');
  menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
  $$('#mainNav a, #mainNav button').forEach(el=>el.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
  $$('[data-scroll]').forEach(el=>el.addEventListener('click',()=>$(el.dataset.scroll)?.scrollIntoView({behavior:'smooth',block:'start'})));
  let selectedPass='Global Pass';
  $$('.pass-option').forEach(button=>button.addEventListener('click',()=>{$$('.pass-option').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');selectedPass=button.dataset.pass;$('#passType').value=selectedPass;$('#previewType').textContent=selectedPass.toUpperCase();}));
  const name=$('#fullName'),birth=$('#birthDate'),country=$('#nationality'),photo=$('#photoInput');
  function updatePreview(){ $('#previewName').textContent=(name.value.trim()||'YOUR NAME').toUpperCase();$('#previewCountry').textContent=(country.value.trim()||'NOT PROVIDED').toUpperCase();$('#previewBirth').textContent=birth.value||'NOT PROVIDED';$('#previewType').textContent=selectedPass.toUpperCase(); }
  [name,birth,country].forEach(el=>el?.addEventListener('input',updatePreview));
  let photoUrl=null;
  photo?.addEventListener('change',()=>{const file=photo.files&&photo.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){photo.value='';alert('Please choose a JPG, PNG or WebP image.');return;}if(file.size>5*1024*1024){photo.value='';alert('Please choose an image smaller than 5 MB.');return;}if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(file);const box=$('#photoPreview');box.textContent='';const img=document.createElement('img');img.src=photoUrl;img.alt='Your selected profile photo';img.style.cssText='width:100%;height:100%;object-fit:cover;border-radius:4px';box.appendChild(img);});
  $('#profileForm')?.addEventListener('submit',e=>{e.preventDefault();if(!$('#confirmData').checked)return;updatePreview();$('#previewMessage').textContent='Preview updated. Please check each detail carefully. This profile is not an official identity document and has not been verified.';$('#digitalPass').scrollIntoView({behavior:'smooth',block:'center'});});
  $('#downloadPreview')?.addEventListener('click',()=>{if(!name.value.trim()){ $('#previewMessage').textContent='Enter your name first, then select “Preview my digital pass”.';return;}window.print();});
  $('#directorySearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();let visible=0;$$('#directoryResults a').forEach(a=>{const show=(a.dataset.search+' '+a.innerText).toLowerCase().includes(q);a.hidden=!show;if(show)visible++;});let empty=$('#noDirectoryResults');if(!visible){if(!empty){empty=document.createElement('p');empty.id='noDirectoryResults';empty.className='inline-message';$('#directoryResults').appendChild(empty);}empty.textContent='No sample listings match that search.';}else empty?.remove();});
  $('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const subject='Digital Future State — '+$('#contactTopic').value;const body='Name: '+$('#contactName').value+'\nEmail: '+$('#contactEmail').value+'\nTopic: '+$('#contactTopic').value+'\n\nMessage:\n'+$('#contactMessage').value;const mailto='mailto:contact@digital-future.ai?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);$('#contactFeedback').textContent='Your email app should open with the message prepared. Review it and press Send there. This website has not sent or stored your message.';window.location.href=mailto;});
  const banner=$('#cookieBanner');$('#cookieSettings')?.addEventListener('click',()=>{banner.hidden=false;});$('#cookieAccept')?.addEventListener('click',()=>{banner.hidden=true;});$('#cookieClose')?.addEventListener('click',()=>{banner.hidden=true;});
  updatePreview();
})();